Feature/ms 06/mongoose/sessions
BaSD-2021/Aquiles-MindSet-server pull request #14
Opened 2021-11-15 03:16 UTC by Micaela-89

**SESSIONS ENTITY**

**Controllers added:**
getAllSessions()
getSessionById()
createNewSession()
updateSession()
deleteSession()

**Request Methods added:**
GET - /sessions
GET - /sessions/:id
POST - /sessions
PUT - /sessions/:id
DELETE - /sessions/:id

2021-11-15 23:11 UTC, Micaela-89 commented
SESSIONS ENTITY

**Controllers added:**
getAllSessions()
getSessionById()
createNewSession()
updateSession()
deleteSession()

**Request Methods added:**
GET - /sessions
GET - /sessions/:id
POST - /sessions
PUT - /sessions/:id
DELETE - /sessions/:id

2021-11-15 23:11 UTC, Micaela-89 commented
SESSIONS ENTITY

**Controllers added:**
getAllSessions()
getSessionById()
createNewSession()
updateSession()
deleteSession()

**Request Methods added:**
GET - /sessions
GET - /sessions/:id
POST - /sessions
PUT - /sessions/:id
DELETE - /sessions/:id

2021-11-19 18:35 UTC, aquilesmariani requested changes
Just small details.

Also, merge development newest changes, add the .env file with the PORT and DARABASE_URL variables as Esteban mentioned on slack.

2021-11-19 18:35 UTC, aquilesmariani commented on models/Sessions.js
> +    postulant_id: {type: mongoose.Schema.Types.ObjectId, ref: 'Postulants'},
I think we should replace this to be camelCase

2021-11-19 18:35 UTC, aquilesmariani commented on postman_collection.json
> +					"raw": "{\r\n    \"date\": \"12/15/2021\",\r\n    \"time\": \"13\",\r\n    \"postulant_id\": \"6192f548af5995b361586c89\",\r\n    \"counselor_id\": \"6191930580595469c7fe1c6f\"\r\n}",
We should modify this so we can send counselorId and postulantId with camelCase

2021-11-19 18:39 UTC, aquilesmariani commented on controllers/sessions.js
> +    return res.status(200).json(`Session with id: ${req.params.id} was deleted`);
It will be nice if you can verify if a counselor was found before returning a 200 message

2021-11-20 13:30 UTC, aquilesmariani reviewed
Looks good @Micaela-89! You still need to merge the development branch into this one so you can fix conflicts. 

Once you do that, it will be ready to merge!

2021-11-20 14:40 UTC, aquilesmariani approved these changes
Looks great!

2021-11-20 14:48 UTC, merged