Feature/ms 05/mongoose/work profile
BaSD-2021/Aquiles-MindSet-server pull request #17
Opened 2021-11-16 00:36 UTC by clementinob

### Work Profile entity:
_Implemented Express Router, new Controller Methods, add folder "`model`"._

Request Methods added:
**GET** - "/"
**GET** - "/:id"
**GET** - "/byName/:name"
**POST** - "/create"
**PUT** - "/update/:id"
**DELETE** - "/delete/:id"

Controllers added:

- `getAllWorkProfiles()`
- `getWorkProfileByID()`
- `getWorkProfilesByName()`
- `createWorkProfile()`
- `updateWorkProfile()`
- `deleteWorkProfile()`

2021-11-17 20:12 UTC, aquilesmariani requested changes

2021-11-17 20:12 UTC, aquilesmariani commented on controllers/work-profiles.js
> +  };
There's no need to put an `else` in this part if you cover the conditional paths with the first `if` 
```suggestion
  if (!req.body.name || !req.body.description) {
    return res.status(400).send('Please include all fields to create a new Work Profile');
  }
  const workProfile = new WorkProfiles({
    name: req.body.name,
    description: req.body.description,
  });
  workProfile.save((error, workProfile) => {
    if (error) {
      return res.status(500).json({ msg: 'Error while creating a new Work Profile', error });
    }
    return res.status(201).json(workProfile);
  });
```

2021-11-17 20:12 UTC, aquilesmariani commented on controllers/work-profiles.js
> +            return res.status(200).json({ msg: `Work Profile with the id: ${req.params.id} was deleted!`, result });
Can we get rid of the `result` we are returning here? I don't see the point of sharing the data we just deleted.

2021-11-17 20:12 UTC, aquilesmariani commented on controllers/work-profiles.js
> +    getAllWorkProfiles : getAllWorkProfiles,
Let's start using `property shorthands` to asign a property any value with the same name:
```suggestion
module.exports = {
    getAllWorkProfiles,
```

2021-11-17 20:12 UTC, aquilesmariani commented on models/work-profiles.js
> +const Schema = mongoose.Schema;
You can import it doing the following:
```suggestion
const { Schema } = mongoose;
```

2021-11-17 20:12 UTC, aquilesmariani commented on models/work-profiles.js
> +		{
Please fix indentation here. You can also place every opening braces on the line above right after the parenthesis.

2021-11-17 20:12 UTC, aquilesmariani commented on router/index.js
> +router.use('/workProfiles',workProfilesRouter);
Separate params with a space after the comma
```suggestion
router.use('/workProfiles', workProfilesRouter);
```

2021-11-17 20:14 UTC, aquilesmariani commented
@clementinob you can also try running `npm run lint` to check the amount of errors you have in your files and fix them before requesting my review again

2021-11-17 20:57 UTC, clementinob commented on postman_collection.json
> +							"raw": "http://localhost:3000/api/workProfiles/6192da2beafe6937464852dc",
Yup, didn't save the collection in Postman before the export. Done. Sorry about that.

2021-11-17 20:58 UTC, clementinob commented on controllers/work-profiles.js
> +  .catch((error) => res.status(500).json(error));
Done!

2021-11-17 21:04 UTC, clementinob commented on controllers/work-profiles.js
> +  };
You are right. Done.

2021-11-17 21:05 UTC, clementinob commented on controllers/work-profiles.js
> +            return res.status(200).json({ msg: `Work Profile with the id: ${req.params.id} was deleted!`, result });
Now that you point it out to me, it makes sense to me. 👍

2021-11-17 21:06 UTC, clementinob commented on controllers/work-profiles.js
> +    getAllWorkProfiles : getAllWorkProfiles,
Right. Done!

2021-11-17 21:08 UTC, clementinob commented on models/work-profiles.js
> +const Schema = mongoose.Schema;
I didn't know that it can be imported like this. Implemented ✅

2021-11-17 21:09 UTC, clementinob commented on models/work-profiles.js
> +		{
✔️

2021-11-17 21:10 UTC, clementinob commented on router/index.js
> +router.use('/workProfiles',workProfilesRouter);
Done. Sorry about that. 👎

2021-11-17 21:38 UTC, clementinob commented
@aquilesmariani Done with the Eslint!

2021-11-18 03:07 UTC, aquilesmariani approved these changes
Looks great!! Nice job!

2021-11-18 20:31 UTC, merged