Feature/MS-01/mongoose/postulants
BaSD-2021/Aquiles-MindSet-server pull request #18
Opened 2021-11-16 01:25 UTC by nailaghigo

**Postulants Entity:**

-Add the following endpoints:

- `GET` => 'app/postulants', => **Get All Postulants**
- `GET` => 'app/postulants/:id', => **Get All Postulants By ID**
- `GET` => 'app/postulants/byLastName/:last_name', => **Get All Postulants By Last Name**
- `POST` => 'app/postulants/add', => **Create a New Postulant**
- `PUT` => 'app/postulants/update/:id', => **Update Postulant Information**
- `DELETE` => 'app/postulants/delete/:id', => **Delete a Postulant**

-Install Mongoose Library and use Queries Like:

- `find()`
- `findById()`
- `findByIdAndUpdate()`
- `findOneAndDelete()`
- `save()`

-Create Postulant Schema

-Use Postman Collection:

![postman](https://user-images.githubusercontent.com/20649442/141875558-4c43298a-5bbe-4162-8fbf-f7547959ed8e.png)

2021-11-20 14:08 UTC, aquilesmariani requested changes
Please review the changes, then rebase and we should check that everything is still working as intended

2021-11-20 14:08 UTC, aquilesmariani commented on controllers/postulants.js
> +  Postulants.findOneAndDelete({ id: req.params.id })
This removes a Postulant no matter which id you send, try using `findByIdAndDelete`

2021-11-20 17:18 UTC, nailaghigo commented on README.md
>  ```
Done!

2021-11-20 17:20 UTC, nailaghigo commented on controllers/postulants.js
> +    first_name: req.body.first_name,
All props names are now updated according to naming conventions mentioned at Slack.

2021-11-22 03:44 UTC, aquilesmariani requested changes

2021-11-22 03:44 UTC, aquilesmariani commented on controllers/postulants.js
> +    })
We should check if the found postulant is null and return a 404
```suggestion
  Postulants.findByIdAndDelete(req.params.id)
    .then((res) => {
      if (!res) return res.status(404).json({ msg: `Postulant with id: ${req.params.id} not found.` });
      return res.send({
        msg: `Postulant with id: ${req.params.id} was succesfully deleted.`,
      });
    })
```

2021-11-22 06:09 UTC, nailaghigo commented on controllers/postulants.js
> +    })
oh ok! thanks for notice that!

2021-11-22 15:09 UTC, aquilesmariani requested changes
Looks great! Thanks for the changes

2021-11-22 15:09 UTC, aquilesmariani approved these changes

2021-11-22 15:11 UTC, merged