BaSD-MS-02: Mongoose/Admins. Add controllers, routes and model (Schema) for Admin entity.
BaSD-2021/Aquiles-MindSet-server pull request #22
Opened 2021-11-20 05:54 UTC by clementinob

### Admin entity:
_Implemented **Express Router**, new **Controllers Methods**, add folder "`model`" with the schema based on Mongoose library, and Postman Collection._

Request Methods added:
**GET** - "/"
**GET** - "/:id"
**GET** - "/byEmail/:email"
**POST** - "/create"
**PUT** - "/update/:id"
**DELETE** - "/delete/:id"

Controllers added:

- `getAllAdmins`,
- `getAdminByID`,
- `getAdminByEmail`,
- `createAdmin`,
- `updateAdmin`,
- `deleteAdmin`

2021-11-22 04:33 UTC, aquilesmariani requested changes

2021-11-22 04:33 UTC, aquilesmariani commented on models/Admins.js
> +  email: { type: String, required: true },
Wondering if we should add a password prop for it. Can we do it or didn't we add it for any reason?

2021-11-22 04:33 UTC, aquilesmariani commented on controllers/admins.js
> +    return res.status(400).json({ msg: 'You should enter an Admin ID to be deleted' });
You could replace the `delete` method and use it like this instead adding multiple `else` or `else if`
```suggestion
const deleteAdmin = (req, res) => {
  if (!req.params.id) return res.status(400).json({ msg: 'You should enter an Admin ID to be deleted' });
  return Admins.findByIdAndDelete(req.params.id, (error, result) => {
    if (error) return res.status(400).json(error);
    if (result === null) return res.status(404).json({ msg: 'Admin ID not found' });
    return res.status(200).json({ msg: `Admin with the id: ${req.params.id} was deleted!` });
  });
};
```

2021-11-22 04:33 UTC, aquilesmariani commented on index.js
> -const interviews = require('./controllers/interviews.js');
After you merge with `development`, is it ok to remove all those imports?

2021-11-22 04:33 UTC, aquilesmariani commented on models/Admins.js
> +  email: { type: String, required: true },
Could we think of a way to add a validation to accept only email formats?

2021-11-22 16:05 UTC, clementinob commented on models/Admins.js
> +  email: { type: String, required: true },
Done! 

- Password prop has been added with a validation of password.length >= 8 characters. 
- Validation of email with the Schema prop "**match**" and a _RegEx_ of email.

2021-11-22 16:06 UTC, clementinob commented on controllers/admins.js
> +    return res.status(400).json({ msg: 'You should enter an Admin ID to be deleted' });
Done! It's very much readable now. Applied on every method with "if and else" statements. 👍

2021-11-22 16:09 UTC, clementinob commented on index.js
> -const interviews = require('./controllers/interviews.js');
My bad, now only removed the `imports `and `app.get` endpoints of entities that has been updated to the `development ` branch

2021-11-23 00:01 UTC, aquilesmariani approved these changes
Nice refactor on the `if` conditions 👏

2021-11-23 02:28 UTC, merged