BaSD-MS-11: feature/MS-11/sessions-View-CRUD.
BaSD-2021/Aquiles-MindSet-server pull request #23
Opened 2021-11-21 17:09 UTC by Micaela-89

Public folder created, with html views, css and js folders inside. 
Sessions htmls (list and form) created and css added

2021-11-22 05:01 UTC, aquilesmariani requested changes
As per discussed in slack, we should refactor the folders so we have entity-related folders inside `public/views`


- styles
- sessions
- admins
- postulants
- ...

Then, inside every folder, include the markup, styles and functionality (index.html, styles.css, app.js)

Also, if you add `app.use(express.static('public'));` into `index.js` file on line 26, you will be able to access those files through `localhost:3000/views/sessions/sessions-list`

2021-11-22 11:32 UTC, Micaela-89 commented on package.json
> +}
Changes done.
Already commited and push them.

2021-11-23 03:08 UTC, Micaela-89 commented
CRUD methods created.

- List Sessions
- Delete Session
- Create Session
- Update Session

2021-11-24 13:42 UTC, aquilesmariani requested changes
Just a few things to address and will be ready to go!

2021-11-24 13:42 UTC, aquilesmariani commented on public/views/sessions/js/sessions-form.js
> +        console.log(response.data);
We should get rid of this console logs

2021-11-24 13:42 UTC, aquilesmariani commented on public/views/sessions/js/sessions-form.js
> +        console.log(response.status)
Same with this one.

2021-11-24 13:42 UTC, aquilesmariani commented on public/views/sessions/js/sessions-list.js
> +  fetch(`http://localhost:3000/api/sessions/${id}`, { method: 'DELETE' })
Still need to replace localhost for `window.location.origin`

2021-11-24 13:42 UTC, aquilesmariani commented on public/views/sessions/js/sessions-list.js
> +  fetch('http://localhost:3000/api/sessions/')
Same on this one.

2021-11-24 20:06 UTC, Micaela-89 commented on public/views/sessions/js/sessions-list.js
> +  fetch(`http://localhost:3000/api/sessions/${id}`, { method: 'DELETE' })
Done!

2021-11-25 00:46 UTC, aquilesmariani approved these changes
Well done Mica!! 🚀

2021-11-25 00:48 UTC, merged