Feature/ms 16/interviews view crud
BaSD-2021/Aquiles-MindSet-server pull request #27
Opened 2021-11-23 03:26 UTC by Brunomoyano4

Create methods for:

- Create interview
- Read interviews
- Update interviews
- Delete interviews

2021-11-24 13:32 UTC, aquilesmariani requested changes

2021-11-24 13:32 UTC, aquilesmariani commented on .gitignore
> +package-lock.json
As we mentioned couple of weeks ago, we are tracking the `package-lock.json` file because heroku needs it in order to make deployments.

2021-11-24 13:45 UTC, Brunomoyano4 commented on .gitignore
> +package-lock.json
Sorry, I had problems with merge, it's an old file of .gitignore . I already modified it

2021-11-25 01:39 UTC, aquilesmariani approved these changes
👏

2021-11-25 01:55 UTC, merged