Applications-and-Positions-Backend-problems-Fixed: working correctly
BaSD-2021/Aquiles-MindSet-server pull request #31
Opened 2021-12-01 12:02 UTC by ManuelLopezAnido

Fixing problems in the backend to applications and positions

2021-12-01 12:51 UTC, ignacioaristo approved these changes
Looks good to me!

2021-12-02 03:35 UTC, aquilesmariani requested changes
Just a few changes to apply

2021-12-02 03:35 UTC, aquilesmariani commented on models/Applications.js
> +  applicationState: "string",
```suggestion
  applicationState: String,
```

2021-12-02 03:35 UTC, aquilesmariani commented on models/Client.js
> +  companyName: { type: String, required: false },
```suggestion
  companyName: String,
```

2021-12-02 03:36 UTC, aquilesmariani commented on models/Positions.js
> +    datePosted: { type: String, required: true },
Did you try parsing the date from the app to the mongoose `Date` type?

2021-12-04 16:15 UTC, leimeterjoaquin approved these changes

2021-12-07 00:10 UTC, aquilesmariani approved these changes
Looks great!

2021-12-07 22:39 UTC, merged