BaSD-MS-20: fix route for interviews
BaSD-2021/Aquiles-MindSet-server pull request #34
Opened 2021-12-05 14:46 UTC by rodrisibrins

2021-12-05 14:49 UTC, ignacioaristo approved these changes

2021-12-07 00:11 UTC, aquilesmariani requested changes

2021-12-07 00:11 UTC, aquilesmariani commented on router/interviews.js
> +interviewsRouter.get('/id/:id', getInterviewsById);
I think it's better to get rid of the `/id`

```suggestion
interviewsRouter.get('/:id', getInterviewsById);
```

2021-12-09 21:01 UTC, leimeterjoaquin approved these changes

2021-12-12 14:56 UTC, aquilesmariani approved these changes

2021-12-14 00:56 UTC, merged