create PostulantId and the respective controllers
BaSD-2021/Aquiles-MindSet-server pull request #40
Opened 2021-12-21 18:16 UTC by ManuelLopezAnido

Creating the new key PostulantId for Interviews and the respective controllers for adding. 
Also adding some new interviews with the new data

2021-12-22 19:09 UTC, aquilesmariani requested changes

2021-12-22 19:09 UTC, aquilesmariani commented on models/Interviews.js
> +    postulantId: { type: mongoose.Schema.Types.ObjectId, ref: 'Postulants' },
I think we should also add a `companyId` to link the model with the companies

2021-12-27 23:01 UTC, aquilesmariani approved these changes
Looks good! 👍

2021-12-27 23:03 UTC, leimeterjoaquin approved these changes

2021-12-28 18:27 UTC, merged